name: "Deploy staging"
"on":
  push:
    branches: [ master ]
jobs:
  build_and_deploy:
    if: ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Enable yarn cache"
        uses: c-hive/gha-yarn-cache@v2  # using cache

      - name: "Setup node@14"
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: "Install dependencies"
        run: |
          yarn set version 3.1.1
          yarn install

      - name: "Build goerli"
        run: yarn run ci:build:goerli

      - name: "Setup node@18"
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: "Deploy target: goerli"
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FORCED_EXIT_STAGING }}"
          target: goerli
          projectId: forced-exit-staging
          channelID: live

      - name: "Setup node@14"
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: "Build mainnet"
        run: yarn run ci:build:mainnet

      - name: "Setup node@18"
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: "Deploy target: mainnet"
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FORCED_EXIT_STAGING }}"
          target: mainnet
          projectId: forced-exit-staging
          channelID: live
